---
  server:
    port: 8080

  spring:
    jpa:
      database: postgresql
      hibernate:
        ddl-auto: update
    datasource:
      url: jdbc:postgresql://localhost:5432/JavaDB
      username: lost
      password: 123
      driver-class-name: org.postgresql.Driver
